Products/urls.py
from django.urls import path
from .views import ProductList, ProductDetail, CategoryList ,CategoryDetail, CommentDetail, CommentList, Favourite_productDetail, Favourite_productList

urlpatterns = [
    path("", ProductList.as_view(), name="Product_list"),
    path("<int:pk>/", ProductDetail.as_view(), name="Product_detail"),
    path("category", CategoryList.as_view(), name="Category_list"),
    path("category/<int:pk>/", CategoryDetail.as_view(), name="Category_detail"),
    path("comment", CommentList.as_view(), name="Comment_list"),
    path("comment/<int:pk>/", CommentDetail.as_view(), name="Comment_detail"),
    path("Favourite_product", Favourite_productList.as_view(), name="Favourite_product_list"),
    path("Favourite_product/<int:pk>/", Favourite_productDetail.as_view(), name="Favourite_product_detail"),


]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .views import SignUpAPIView


# from .views import SignUpView

urlpatterns = [
    # path("signup/", SignUpView.as_view(), name="signup"),
    path('signup/', SignUpAPIView.as_view(), name='signup')
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from .views import MyTokenObtainPairView
from django.views.generic.base import TemplateView
from django.conf.urls.static import static         #
from django.conf import settings       #


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/Products/", include("Products.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "api/token/",
        MyTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path("Products/", include("Products.urls_front")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("account/", include("account.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse




class Category(models.Model):
    owner = models.ForeignKey(get_user_model(),on_delete=models.CASCADE, null=True, blank=True)
    category_type = models.CharField(max_length=256)

    def __str__(self):
        return self.category_type


class Product(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    Title = models.CharField(max_length=256)
    image= models.ImageField(upload_to='uploads/', blank=True,null=True)
    description = models.TextField(default="", null=True, blank=True)
    price = models.IntegerField()
    contact_info = models.CharField(max_length=256)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
        return self.Title

    def get_absolute_url(self):
        return reverse('Product_detail', args=[str(self.id)])


class Comment(models.Model):
    owner = models.ForeignKey(get_user_model(),on_delete=models.CASCADE, null=True, blank=True)
    Product = models.ForeignKey(Product,on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.body


class Favourite_product(models.Model):
    owner = models.ForeignKey(get_user_model(),on_delete=models.CASCADE, null=True, blank=True)
    Product = models.ForeignKey(Product,on_delete=models.CASCADE, null=True, blank=True)
    class Meta:
        unique_together = ('owner', 'Product')

    def __str__(self):
        return self.Product.Title

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username=models.CharField(max_length=255,unique=True)
    email=models.EmailField(max_length=255,unique=True)
    
    
    # add additional fields in here

    def __str__(self):
        return self.username

Products/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework import viewsets,generics, permissions
from .models import Product,Category,Comment,Favourite_product
from .permissions import IsOwnerOrReadOnly,IsOwnerOnly
from .serializers import ProductSerializer,CategorySerializer,CommentSerializer,Fav_productSerializer,ProductImageSerializer
# views.py



class ProductImageView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductImageSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]  # Adjust permission as needed

 #1
class ProductList(ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = Product.objects.all()
    serializer_class = ProductSerializer



 #2
class CategoryList(ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class CategoryDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = Category.objects.all()
    serializer_class = CategorySerializer




 #3
class CommentList(ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class CommentDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer



 #4
class Favourite_productList(ListCreateAPIView):
    permission_classes = (IsOwnerOnly,)
    queryset = Favourite_product.objects.all()
    serializer_class = Fav_productSerializer


class Favourite_productDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOnly,)
    queryset = Favourite_product.objects.all()
    serializer_class = Fav_productSerializer

# class Favourite_productList(ListCreateAPIView):
#     permission_classes = [IsOwnerOnly]
#     queryset = Favourite_product.objects.all()
#     serializer_class = Fav_productSerializer


# class Favourite_productDetail(RetrieveUpdateDestroyAPIView):
#     permission_classes = [IsOwnerOnly]
#     queryset = Favourite_product.objects.all()
#     serializer_class = Fav_productSerializer

account/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import UserSerializer

class SignUpAPIView(APIView):
    def post(self, request):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            # Retrieve the password from the validated data
            password = serializer.validated_data.get('password')

            # Create a new user instance without saving it yet
            user = serializer.save()

            # Set the password for the user (this will automatically hash it)
            user.set_password(password)

            # Save the user instance with the hashed password
            user.save()

            return Response({'message': 'User successfully registered'}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# from rest_framework import status
# from rest_framework.response import Response
# from rest_framework.views import APIView
# from .serializers import UserSerializer



# class SignUpAPIView(APIView):
#     def post(self, request):
#         serializer = UserSerializer(data=request.data)
#         if serializer.is_valid():
#             user = serializer.save()
#             return Response({'message': 'User successfully registered'}, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

project/views.py
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView



class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token["email"] = user.email
        token["username"] = user.username
        
        # ...

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

templates/Products/Product_create.html
{% extends 'base.html' %}

{% block content %}
  <div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a Product</h5>
      {{ form.as_p }}

      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>
    </form>
  </div>
{% endblock content %}

templates/Products/Product_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete a Product</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Do you really want to delete "{{ object.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/Products/Product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="space-y-8 p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
  <div class="flex items-center justify-between mb-4">
    <h5 class="text-2xl font-bold text-gray-900 dark:text-white">{{ object.owner }}</h5>
    <div class="flex gap-2">
      <form class="space-y-6" method="post" action="{% url 'product_update' object.pk %}">
        {% csrf_token %}
        <button type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-red-600">
            <!-- ... -->
          </svg>
        </button>
      </form>
      <form method="post" action="{% url 'product_delete' object.pk %}">
        {% csrf_token %}
        <button type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-red-600">
            <!-- ... -->
          </svg>
        </button>
      </form>
    </div>
  </div>
  <h5 class="text-md font-bold text-gray-900 dark:text-white">Ownerd by: {{ object.owner }}</h5>
  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ object.description }}</p>
  <!-- ... other details ... -->
</div>
<a href="{% url 'product_delete' object.pk %}"><button type="button" > Delete
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"  class="w-6 h-6 text-blue-600"></svg></button></a>
        <a href="{% url 'product_update' object.pk %}"><button type="button" > Update
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"  class="w-6 h-6 text-blue-600"></svg></button></a>
        {% endblock content %}

templates/Products/Product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="space-y-8 p-8">

    <h1 class="text-4xl text-center">All the Products</h1>
    <div
      class="w-1/2 mx-auto text-sm font-medium text-gray-900 bg-gray-50 border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
      {% for x in Products%}

        <a href="{% url 'product_detail' x.pk %}" 
           class="block w-full px-4 py-4 text-black bg-blue-600 border-b border-gray-200 rounded-t-lg cursor-pointer dark:bg-gray-800 dark:border-gray-600">
          {{x.Title}}
          <img src="{{ x.image.url }}" alt="{{ x.Title }}" class="w-24 h-24 object-cover" />
        </a>
                <a href="{% url 'product_delete' x.pk %}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-red-600">
            <!-- ... -->
          </svg>
        </a>
      {% endfor %}
    </div>

  </div>

{% endblock content %}

templates/Products/Product_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Product</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Product</h5>
      <div>
        <label for="id_Title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title</label>
        <input type="text" name="name" id="id_Title"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ Product.Title}}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ Product.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_owner" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">owner</label>
        <select name="owner" id="id_owner">
          {% for value, choice in form.fields.owner.choices %}
            <option value="{{ value }}" {% if value == Product.owner.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ Product.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="w-3/4 mx-auto max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="flex justify-end px-4 pt-4">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2" aria-labelledby="dropdownButton">
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Edit</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Export Data</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete</a>
            </li>
            </ul>
        </div>
    </div>
    <div class="flex flex-col items-center pb-10 px-4">
        <img class="w-96 h-96 mb-3 rounded-full shadow-lg" src="https://placekeanu.com/200/150" alt="Keanu image"/>
        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Not Keanu Reeves</h5>
        <span class="text-sm text-gray-500 dark:text-gray-400">Full Stack Developer</span>
        <div class="flex mt-4 space-x-3 md:mt-6">
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add friend</a>
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700">Message</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}All the Products{% endblock %}</title>
 <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-green-50">
<header>
  <nav class="bg-gray-900 border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
        <div class="container flex flex-wrap items-center justify-between mx-auto">
          <a href="{% url 'home' %}">
              <img src="https://upload.wikimedia.org/wikipedia/commons/7/78/Products_Logo.svg" class="p-3 h-12 bg-white rounded" alt="Logo" />
          </a>
          <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
            <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}" class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent  md:p-0 dark:text-white" aria-current="page">Log Out</a>
              </li>
              {% else %}
              <li>
                <a href="{% url 'login' %}" class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent  md:p-0 dark:text-white" aria-current="page">Log In</a>
              </li>
            {% endif %}

              <li>
                <a href="{% url 'about' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
              </li>
              {% if request.user.is_authenticated %}
                <li>
                <a href="{% url 'Product_list' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">List</a>
                </li>
                 <li>
                <a href="{% url 'Product_create' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Create</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
</header>
<main>
<div class="container mx-auto mt-4">
  {% block content %}
  {% endblock content %}
</div>
</main>
<footer
      class="bg-gray-900
             text-sm text-white
             fixed
             inset-x-0
             bottom-0
             p-2">
      &copy; CodeFellows 2023
    </footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}All the Products - Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <div class="space-y-8">

      <h2 class="text-4xl">Hi {{ user.username }}!</h2>
      <p>Maybe one day you'll see a glorious home page here.</p>
      <p>But for now just notice that List and Create are in Nav bar.</p>
    </div>

  {% else %}

    <div class="">
      <div class="hero-content flex bg-red-300 p-4 space-x-4">
        {#  Thanks to https://unsplash.com/photos/Kw_zQBAChws?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink#}
        <img src="{% static 'ashim-d-silva-Products.jpg' %}" class="max-w-sm rounded-lg shadow-2xl"/>
        <div class="bg-green-300 p-4">
          <h1 class="text-5xl font-bold">Products</h1>
          <p class="text-2xl p-6">Almanac, binder, cucumber, drill, envelope, friend, grill, hay, jam, koala, lanyard, mousetrap, necklace, oil, printer, quill, restroom, saline, treasure, wings, xylophone, zebra, and more!</p>
          <a href="{% url 'login' %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Get Started</a>
        </div>
      </div>
    </div>

  {% endif %}
{% endblock %}

templates/things/thing_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Product</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ Product.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/things/thing_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update Product</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a Product</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ Product.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ Product.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == Product.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ Product.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}